# Generated by Django 5.1.5 on 2025-06-28 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_id", models.TextField(unique=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("birth_date", models.TextField(blank=True, null=True)),
                ("sex", models.TextField(blank=True, null=True)),
                ("ethnicity", models.TextField(blank=True, null=True)),
                ("weight", models.TextField(blank=True, null=True)),
                ("age", models.TextField(blank=True, null=True)),
                ("extra_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("series_instance_uid", models.TextField(unique=True)),
                ("modality", models.TextField(blank=True, null=True)),
                ("series_number", models.TextField(blank=True, null=True)),
                ("series_description", models.TextField(blank=True, null=True)),
                ("body_part_examined", models.TextField(blank=True, null=True)),
                ("canonical_instance_count", models.IntegerField()),
                ("healthimaging_imageset_id", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("full_name", models.TextField(blank=True, null=True)),
                ("role", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sop_instance_uid", models.TextField(unique=True)),
                ("content_hash", models.TextField()),
                ("instance_number", models.TextField(blank=True, null=True)),
                ("file_key", models.TextField(blank=True, null=True)),
                ("pixel_spacing", models.TextField(blank=True, null=True)),
                ("slice_thickness", models.TextField(blank=True, null=True)),
                ("image_position_patient", models.TextField(blank=True, null=True)),
                ("image_orientation_patient", models.TextField(blank=True, null=True)),
                ("frame_of_reference_uid", models.TextField(blank=True, null=True)),
                ("window_center", models.TextField(blank=True, null=True)),
                ("window_width", models.TextField(blank=True, null=True)),
                ("bits_allocated", models.TextField(blank=True, null=True)),
                ("bits_stored", models.TextField(blank=True, null=True)),
                ("columns", models.TextField(blank=True, null=True)),
                ("rows", models.TextField(blank=True, null=True)),
                ("photometric_interpretation", models.TextField(blank=True, null=True)),
                ("sop_class_uid", models.TextField(blank=True, null=True)),
                ("number_of_frames", models.IntegerField(blank=True, null=True)),
                ("has_pixel_data", models.BooleanField(blank=True, null=True)),
                ("total_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="api.series",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("study_instance_uid", models.TextField(unique=True)),
                ("study_id", models.TextField(blank=True, null=True)),
                ("study_date", models.TextField(blank=True, null=True)),
                ("study_time", models.TextField(blank=True, null=True)),
                ("study_description", models.TextField(blank=True, null=True)),
                ("accession_number", models.TextField(blank=True, null=True)),
                ("referring_physician_name", models.TextField(blank=True, null=True)),
                ("modality", models.TextField(blank=True, null=True)),
                ("body_part_examined", models.TextField(blank=True, null=True)),
                (
                    "total_study_size_bytes",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="api.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="series",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="api.study",
            ),
        ),
        migrations.CreateModel(
            name="UserSeriesAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_access",
                        to="api.series",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_access",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "series")},
            },
        ),
    ]
