# Generated by Django 5.1.5 on 2025-06-19 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("sex", models.TextField(blank=True, null=True)),
                ("age", models.TextField(blank=True, null=True)),
                ("weight", models.TextField(blank=True, null=True)),
                ("birth_date", models.TextField(blank=True, null=True)),
                ("extra_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.TextField(blank=True, null=True)),
                ("full_name", models.TextField(blank=True, null=True)),
                ("role", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "study_instance_uid",
                    models.TextField(primary_key=True, serialize=False),
                ),
                ("study_id", models.TextField(blank=True, null=True)),
                ("study_date", models.TextField(blank=True, null=True)),
                ("study_time", models.TextField(blank=True, null=True)),
                ("study_description", models.TextField(blank=True, null=True)),
                ("accession_number", models.TextField(blank=True, null=True)),
                ("referring_physician_name", models.TextField(blank=True, null=True)),
                ("modality", models.TextField(blank=True, null=True)),
                ("body_part_examined", models.TextField(blank=True, null=True)),
                (
                    "total_study_size_bytes",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="api.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "series_instance_uid",
                    models.TextField(primary_key=True, serialize=False),
                ),
                ("series_number", models.TextField(blank=True, null=True)),
                ("series_description", models.TextField(blank=True, null=True)),
                ("modality", models.TextField(blank=True, null=True)),
                ("body_part_examined", models.TextField(blank=True, null=True)),
                ("number_of_instances", models.IntegerField(blank=True, null=True)),
                ("sop_instance_uid_list", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "study",
                    models.ForeignKey(
                        db_column="study_instance_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="api.study",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "sop_instance_uid",
                    models.TextField(primary_key=True, serialize=False),
                ),
                ("instance_number", models.TextField(blank=True, null=True)),
                ("file_key", models.TextField(blank=True, null=True)),
                ("pixel_spacing", models.TextField(blank=True, null=True)),
                ("slice_thickness", models.TextField(blank=True, null=True)),
                ("image_position_patient", models.TextField(blank=True, null=True)),
                ("image_orientation_patient", models.TextField(blank=True, null=True)),
                ("frame_of_reference_uid", models.TextField(blank=True, null=True)),
                ("window_center", models.TextField(blank=True, null=True)),
                ("window_width", models.TextField(blank=True, null=True)),
                ("bits_allocated", models.TextField(blank=True, null=True)),
                ("bits_stored", models.TextField(blank=True, null=True)),
                ("columns", models.TextField(blank=True, null=True)),
                ("rows", models.TextField(blank=True, null=True)),
                ("photometric_interpretation", models.TextField(blank=True, null=True)),
                ("sop_class_uid", models.TextField(blank=True, null=True)),
                ("number_of_frames", models.IntegerField(blank=True, null=True)),
                ("has_pixel_data", models.BooleanField(blank=True, null=True)),
                ("total_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="api.patient",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        db_column="series_instance_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="api.series",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        db_column="study_instance_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="api.study",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
