# Generated by Django 5.1.5 on 2025-06-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="study_instance_uid_list",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="study",
            name="series_instance_uid_list",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
