# Generated by Django 5.1.5 on 2025-07-02 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_id_user_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="role",
            new_name="license_id",
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_complete",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="specialty",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "institution_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("institution_type", models.TextField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("contact_phone", models.TextField(blank=True, null=True)),
                ("accreditation_id", models.TextField(blank=True, null=True)),
                ("healthimaging_datastore_id", models.TextField(blank=True, null=True)),
                ("provisioned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.TextField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_user",
                        to="api.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_institution",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
