# Generated by Django 5.1.5 on 2025-06-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_patient_study_instance_uid_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="series",
            name="number_of_instances",
        ),
    ]
