# Generated by Django 5.1.5 on 2025-06-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_series_number_of_instances"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="study_instance_uid_list",
        ),
        migrations.RemoveField(
            model_name="series",
            name="sop_instance_uid_list",
        ),
        migrations.RemoveField(
            model_name="study",
            name="series_instance_uid_list",
        ),
    ]
