# Generated by Django 5.1.5 on 2025-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_patient_study_instance_uid_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ethnicity",
            field=models.TextField(blank=True, null=True),
        ),
    ]
