import { createSlice } from '@reduxjs/toolkit';

const storedUser = localStorage.getItem('user')
    ? JSON.parse(localStorage.getItem('user'))
    : null;

const initialState = {
    user: storedUser,
};

const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        setUser: (state, action) => {
            state.user = action.payload;
            localStorage.setItem('user', JSON.stringify(action.payload)); // Persist data
        },
        clearUser: (state) => {
            state.user = null;
            localStorage.removeItem('user');
        },
    },
})

// Export the actions generated by createSlice
export const { setUser, clearUser } = userSlice.actions;
// Export the reducer to be used in the store
export default userSlice.reducer;